#!/usr/bin/env python3


import argparse

import maze


def getArguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("--height", type=int, required=False, default=800,
                        help="Height of the application in pixels.")
    parser.add_argument("--tiles", type=int, required=False, default=10,
                        help="How many tiles each side should be divided into.")
    parser.add_argument("--width", type=int, required=False, default=1200,
                        help="Width of the application in pixels.")
    parser.add_argument("--fps", type=int, required=False, default=60,
                        help="The max framerate of the game.")
    parser.add_argument("--debug", required=False, default=False,
                        action="store_true",
                        help="Makes the application become more verbose.")
    parser.add_argument("--food", required=False, default=3,
                        help="The number of food items on screen at any given time.")
    parser.add_argument("--foodpoint", required=False, default=10,
                        help="The number of points for eating food.")

    return parser.parse_args()


if __name__ == "__main__":

    args = getArguments()
    maze = maze.Maze(args)
    maze.run()
